Results of doctest builder run on 2024-10-05 21:11:55
=====================================================

Document: apidoc/classes
------------------------
**********************************************************************
File "../openket/core/diracobject.py", line ?, in default
Failed example:
    x = var("x")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1361, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        x = var("x")
            ^^^
    NameError: name 'var' is not defined. Did you mean: 'vars'?
**********************************************************************
File "../openket/core/diracobject.py", line ?, in default
Failed example:
    v = Ket(x)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1361, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[1]>", line 1, in <module>
        v = Ket(x)
            ^^^
    NameError: name 'Ket' is not defined. Did you mean: 'set'?
**********************************************************************
File "../openket/core/diracobject.py", line ?, in default
Failed example:
    v
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1361, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[2]>", line 1, in <module>
        v
    NameError: name 'v' is not defined
**********************************************************************
File "../openket/core/diracobject.py", line ?, in default
Failed example:
    u = Ket(1,"Op1")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1361, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        u = Ket(1,"Op1")
            ^^^
    NameError: name 'Ket' is not defined. Did you mean: 'set'?
**********************************************************************
File "../openket/core/diracobject.py", line ?, in default
Failed example:
    w = Ket(1,"Op2")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1361, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[1]>", line 1, in <module>
        w = Ket(1,"Op2")
            ^^^
    NameError: name 'Ket' is not defined. Did you mean: 'set'?
**********************************************************************
File "../openket/core/diracobject.py", line ?, in default
Failed example:
    u,w
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/doctest.py", line 1361, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[2]>", line 1, in <module>
        u,w
        ^
    NameError: name 'u' is not defined
**********************************************************************
1 items had failures:
   6 of   6 in default
6 tests in 1 items.
0 passed and 6 failed.
***Test Failed*** 6 failures.

Doctest summary
===============
    6 tests
    6 failures in tests
    0 failures in setup code
    0 failures in cleanup code
